---
model_architecture: CANFHyperPriorCoderWithTemporalPrior

model_params:
    num_filters: 72
    num_features: 128
    num_hyperpriors: 128
    hyper_filters: 128
    in_channels: 3
    out_channels: 3
    kernel_size: 5
    num_layers: 2
    init_code: gaussian
    use_QE: True
    use_affine: False
    use_mean: True
    use_context: False
    condition: Gaussian
    quant_mode: noise
    in_channels_tp: 3
    num_filters_tp: 72
