---
model_architecture: GoogleHyperPriorCoder

model_params:
    num_filters: 128
    num_features: 128
    num_hyperpriors: 128
    in_channels: 2
    out_channels: 2
    kernel_size: 3
    use_mean: True
    use_context: False
    condition: Gaussian
    quant_mode: noise
